name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  screenshot-ubuntu:
    name: Screenshot (Ubuntu)
    strategy:
      matrix:
        os: [ubuntu-latest]
        width: [1200, 992, 768, 600]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Capture Screenshot
      id: screenshot
      uses: ./
      with:
        source: https://github.com/swinton/screenshot-website
        destination: github-com-swinton-screenshot-website-${{ matrix.os }}-${{ matrix.width }}.png
        full-page: true
        width: ${{ matrix.width }}

  screenshot-macos:
    name: Screenshot (macOS)
    strategy:
      matrix:
        os: [macos-latest]
        width: [1200, 992, 768, 600]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Capture Screenshot
      id: screenshot
      uses: ./
      with:
        source: https://github.com/swinton/screenshot-website
        destination: github-com-swinton-screenshot-website-${{ matrix.os }}-${{ matrix.width }}.png
        full-page: true
        width: ${{ matrix.width }}

  screenshot-windows:
    name: Screenshot (Windows)
    strategy:
      matrix:
        os: [windows-latest]
        width: [1200, 992, 768, 600]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Capture Screenshot
      id: screenshot
      uses: ./
      with:
        source: https://github.com/swinton/screenshot-website
        destination: github-com-swinton-screenshot-website-${{ matrix.os }}-${{ matrix.width }}.png
        full-page: true
        width: ${{ matrix.width }}

  screenshot-no-width:
    name: Screenshot (no width)
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Capture Screenshot
      id: screenshot
      uses: ./
      with:
        source: https://github.com/swinton/screenshot-website
        destination: github-com-swinton-screenshot-website-ubuntu-latest-default.png
        full-page: true
